export const surpriseMePrompts = [
  "A futuristic cityscape with glowing neon lights at night",
  "A dragon resting on a mountain peak under a starry sky",
  "A cozy cabin surrounded by a magical snow-covered forest",
  "An underwater scene with mermaids, coral reefs, and sunken treasure",
  "A steampunk airship flying over a victorian-style city",
  "A mystical creature with wings made of fire and ice",
  "A robotic cat playing with a futuristic laser ball",
  "A fairytale castle floating on clouds with a rainbow bridge",
  "A bustling alien marketplace on a distant planet",
  "A serene Japanese garden in autumn with koi ponds and red maple trees",
  "A pirate ship sailing through a storm with lightning illuminating the scene",
  "A magical book glowing with golden light in a dark library",
  "An enchanted tree with doors, windows, and tiny fairy inhabitants",
  "A time traveler stepping out of a glowing portal into the future",
  "A superhero flying over a cityscape at sunset",
  "A desert oasis with a mysterious glowing artifact at its center",
  "A warrior riding a giant wolf through a snowy tundra",
  "An ancient temple hidden in a lush jungle with waterfalls",
  "A surreal landscape with floating islands and upside-down rivers",
  "A futuristic train speeding through a cyberpunk metropolis",
  "A giant octopus wrapping its tentacles around a lighthouse during a storm",
  "A futuristic underwater city glowing in the deep ocean",
  "A magical mirror reflecting a parallel universe",
  "A whimsical hot air balloon festival in a fantasy world",
  "A knight in shining armor battling a shadowy monster",
  "A carnival at night with glowing rides and colorful lights",
  "A lone astronaut standing on an alien planet with two suns",
  "A serene mountain landscape with a clear blue lake at sunrise",
  "A robot tending to a garden of glowing bioluminescent flowers",
  "A space station orbiting a gas giant with stunning auroras",
  "A phoenix rising from its fiery ashes in an epic scene",
  "A futuristic city submerged underwater, teeming with aquatic life",
  "A magical waterfall flowing into a glowing crystal cavern",
  "A giant turtle carrying an entire forest on its back",
  "A surreal dreamscape with floating clocks and melting landscapes",
  "A cozy coffee shop in a steampunk-inspired world",
  "A mysterious lighthouse glowing on the edge of an endless ocean",
  "A celestial palace made entirely of shimmering stars",
  "A vibrant market street during a festive celebration in a fantasy village",
  "A wizard casting a spell in an ancient ruin filled with glowing runes",
  "A panda samurai meditating under a cherry blossom tree",
  "A futuristic racecar speeding through a neon-lit track",
  "A tiny village built inside a giant tree's trunk",
  "A flying whale soaring above a peaceful ocean at sunset",
  "A magical forest with glowing mushrooms and enchanted creatures",
  "A spaceship landing on a red, alien desert with tall crystal spires",
  "A charming scene of a hobbit-style home built into a hillside",
  "A cyberpunk-style robot bartender mixing glowing drinks",
  "A peaceful meadow with a unicorn grazing under a rainbow",
  "A surreal cityscape with impossible architecture and Escher-like elements",
];
