export const surpriseMePrompts = [
  "A futuristic cityscape glowing with neon holograms, flying cars weaving through skyscrapers under a stormy purple sky",
  "A majestic dragon perched on a crystalline mountain peak, illuminated by a galaxy of stars and auroras",
  "A cozy cabin deep in a snow-covered enchanted forest, smoke curling from the chimney and magical lights dancing between the trees",
  "An underwater kingdom with mermaids, glowing coral reefs, giant sea turtles, and a sunken treasure ship",
  "A massive steampunk airship with brass gears and steam vents, drifting over a Victorian skyline at sunset",
  "A mystical phoenix-like creature with wings of fire and ice, soaring across a volcanic horizon",
  "A sleek robotic cat with glowing eyes playing with a hovering neon laser orb in a futuristic apartment",
  "A fairytale castle floating among clouds, connected by a shimmering rainbow bridge to distant islands",
  "A bustling alien marketplace on a distant planet, filled with exotic foods, glowing stalls, and otherworldly creatures",
  "A serene Japanese garden in autumn, koi ponds glowing softly under lantern light and red maple leaves falling around",
  "A pirate ship braving a violent storm, waves crashing as lightning reveals a ghostly sea monster",
  "An ancient library with shelves stretching into infinity, a magical book glowing with golden runes at its center",
  "A colossal enchanted tree with glowing windows and doors, tiny fairy villages built within its branches",
  "A time traveler emerging from a glowing portal into a futuristic cyberpunk street filled with neon lights",
  "A superhero soaring above a glowing metropolis at sunset, cape billowing in the wind",
  "A hidden desert oasis with crystalline waters, a mysterious artifact floating and radiating light at its center",
  "A warrior in fur armor riding a massive dire wolf through a snowy tundra under an aurora sky",
  "An ancient jungle temple overgrown with vines, waterfalls cascading down glowing moss-covered stones",
  "A surreal dreamscape of floating islands, upside-down rivers, and giant glowing moons in the sky",
  "A futuristic maglev train racing through a neon-lit cyberpunk city at night",
  "A colossal octopus coiled around a lighthouse, lightning illuminating the raging sea",
  "A glowing futuristic underwater city enclosed in a shimmering dome, teeming with alien marine life",
  "A magical mirror reflecting a parallel universe where everything is inverted and glowing with strange colors",
  "A whimsical hot air balloon festival with floating castles, dragons, and giant jellyfish in the sky",
  "A knight in gleaming armor clashing with a shadowy monster in a battlefield of burning ruins",
  "A carnival at night filled with glowing rides, colorful lanterns, and enchanted performers",
  "A lone astronaut standing on a red alien planet, gazing at twin suns rising over jagged crystal spires",
  "A tranquil mountain lake at sunrise, mist rolling across the water as deer drink peacefully",
  "A gentle robot tending a garden of glowing bioluminescent plants beneath a futuristic glass dome",
  "A colossal space station orbiting a gas giant with breathtaking auroras sweeping across its atmosphere",
  "A phoenix rising in a blaze of fire, scattering sparks across a starry cosmic background",
  "A futuristic metropolis submerged underwater, skyscrapers glowing while schools of fish swim through the streets",
  "A mystical waterfall cascading into a glowing cavern filled with giant crystal formations",
  "A massive turtle carrying an entire enchanted forest on its shell as it swims across the ocean",
  "A surreal landscape of melting mountains, floating clocks, and shifting dreamlike skies",
  "A cozy steampunk-inspired café with brass pipes, glowing lamps, and people sipping coffee among inventions",
  "A lonely lighthouse glowing on the edge of an endless stormy ocean, surrounded by ghostly ships",
  "A celestial palace made of shimmering stars and constellations floating above the galaxy",
  "A vibrant festival street in a fantasy village, glowing lanterns, enchanted fireworks, and musicians playing magical instruments",
  "A wizard casting an ancient spell, glowing runes floating around as the ruins tremble with power",
  "A samurai panda meditating under a cherry blossom tree, petals glowing as they fall into a koi pond",
  "A futuristic neon racecar blazing through a glowing track suspended in the sky",
  "A tiny village carved inside a giant tree’s trunk, lanterns glowing among bridges and stairways",
  "A flying whale gliding gracefully across the sunset sky above a calm ocean",
  "A magical glowing forest filled with bioluminescent mushrooms, spirits, and enchanted creatures",
  "A spaceship landing on a red desert planet with massive crystal spires and alien flora",
  "A cozy hobbit-style home built into a hillside, smoke curling from the chimney under a twilight sky",
  "A cyberpunk robot bartender mixing glowing drinks in a neon-lit underground bar",
  "A unicorn grazing in a peaceful meadow under a rainbow arching across a waterfall",
  "An impossible Escher-style city with staircases twisting in all directions and gravity-defying architecture",

  // ✨ New 10 extra prompts:
  "A cosmic dragon made of galaxies and starlight spiraling across deep space",
  "A futuristic sky garden built on floating platforms, glowing waterfalls pouring into the clouds",
  "A mystical desert caravan traveling under three glowing moons with sand shimmering like gold",
  "A giant clock tower powered by magic, gears spinning and floating above a steampunk city",
  "An enchanted ice palace glowing with blue crystals, surrounded by auroras in the polar night",
  "A cyberpunk samurai standing on a neon-lit rooftop with holographic cherry blossoms falling",
  "A colossal library spaceship drifting through the stars, filled with glowing knowledge orbs",
  "A surreal canyon where rivers flow upward into the sky, glowing with rainbow mists",
  "A magical forest spirit emerging from ancient stone ruins, glowing with emerald energy",
  "A futuristic carnival floating in space, with zero-gravity rides and glowing neon attractions"
];
